/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class MainTest {
    
}
