/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());

        System.out.println("Hello world!");
        try (
                Connection c = DriverManager.getConnection("jdbc:h2:./test", "", "");
                Statement stmt = c.createStatement();) {
            Class.forName("org.h2.Driver");
            stmt.execute("CREATE TABLE IF NOT EXISTS ejemplo (id INT PRIMARY KEY, nombre VARCHAR(255))");
            System.out.println("Connected to H2 database.");
        } catch (ClassNotFoundException e) {
            System.err.println("Database driver not found: " + e.getMessage());
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
